services:
  jupyter:  # you can change this to whatever you want.
    build:
      dockerfile: cuda.Dockerfile
    container_name: keras_cuda10
    image: tensorflow/tensorflow:custom-op-gpu-ubuntu16-cuda10.0
    volumes:
      - "./:/tf/notebooks"
    ports:
     - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
          -  driver: nvidia
             count: all
             capabilities: [gpu]
