services:
  gdal:  # you can change this to whatever you want.
    container_name: gdal
    image: andrejreznik/python-gdal:stable
    build:
      dockerfile: gdal.Dockerfile
    volumes:
      - "./:/tf/notebooks"
    ports:
     - "8888:8888"